#Sets the flags for the C compiler.
#-g=debugging symbols, -Wall=all warnings (not really all), -std=c99 use
#the C99 standard.
CFLAGS= -g -Wall -std=c99

#A target that cleans up the executable.
clean:
	rm -f ex1
