#Sets the flags for the C compiler.
#-g=debugging symbols, -Wall=all warnings (not really all), -std=c99 use
#the C99 standard, -m32=compile as 32bit
CFLAGS= -g -Wall -std=c99 -m64
LDFLAGS=-m64

#A target that cleans up the executable.
clean:
	rm -f ex3
